### ISSUE TITLE
[SOLVED]: Cannot get contract. CATCH ERROR: NOK: Transaction not found with hash

### ISSUE THREAD

**Issue by ZnXCreators** [codeSTACKr/create-10k-nft-collection#118]
***UPDATE: Problem resolved overnight. Contract now deployed and getting all info, but it took over 6 hours. Likely was an issue with Rinkeby testnet or servers at NFTPort?***
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

Working from latest 2.0.0 repo, following instructions as is as per "How To Create An ENTIRE NFT Collection (10,000+) & MINT With ZERO Coding Knowledge - v2.0.0"

Everything going will up to  
$ npm run deploy_contract

I even see a Contract subfolder has been created in the Build folder.
But getting error msg with: $ npm run get_contract  
Getting error msg CATCH ERROR: NOK: Transaction not found. Log below.

PLEASE HELP. I see other users, inc. #114 and #110 have the same issue. Thanks!

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
Retrying
CATCH ERROR: NOK: Transaction not found with hash

CATCH ERROR: ERROR STATUS: 502
```

### Protect your information

- [X] I Agree

**Comment by Warman8264** [comment]
@ZnXCreators what was the solution to the transaction hash not being found.

**Comment by cmapez** [comment]
Okay so essentially it means the NFT Port server is down and you just have to message the NFT port discord about it

**Comment by adrianmaull** [comment]
I get the same error.  I was successfully able to get a contract on Rinkeby.  But not yet on Polygon.  The solution is to post on NFTPort's Discord server?

**Comment by Warman8264** [comment]
@cmapez Where did you find the NFT port discord?
