### ISSUE TITLE
[Bug]: no ipfs folder created, even though upload says successfull 

### ISSUE THREAD

**Issue by r3lla** [codeSTACKr/create-10k-nft-collection#119]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

I was going per instruction, with all files being said to have been uploaded. 

Thus, I porceeded to creating the contract, getting it and wanted to start to mint. 

However, at minting stage is where program could not find the ipfsMetas directory and I went on to the build folder and noticed that the ipfs folder was never created. 

Even though, the contract & mint folder are already there. 

Whenever I try to run the upload command again, it starts listing all files saying uploaded. However, no ipfs directory in build still. 

I had my API key with hyphens initially, then I removed the hyphens and replaced with spaces.
![err2](https://user-images.githubusercontent.com/101604415/158405076-1f07561e-9a4d-4694-bc7b-0f2cb87a7c27.jpg)
![err1](https://user-images.githubusercontent.com/101604415/158405084-78c31262-8fed-489a-bb8b-058029b90c5d.jpg)

### What have you tried?

Tried to look through the readme and read the support on the program's GitHub 

### Relevant log output

```shell
node:fs:585
  handleErrorFromBinding(ctx);
ion-2.0.0/build/ipfsMetas/_ipfsMetas.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at main (C:\Users\37369\Desktop\create-10k-nft-collection-2.0.0\utils\nftport\mint.js:43:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\37369\\Desktop\\create-10k-nft-collection-2.0.0/build/ipfsMetas/_ipfsMetas.json'
```

### Protect your information

- [x] I Agree

**Comment by vcrcreative** [comment]
What was the solution!?
