### ISSUE TITLE
[Bug]:  CATCH ERROR: NOK: Contract limit exceeded on rinkeby Retrying

### ISSUE THREAD

**Issue by StartUpDream** [codeSTACKr/create-10k-nft-collection#128]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened!

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
CATCH ERROR: NOK: Contract limit exceeded on rinkeby
Retrying
```

### Protect your information

- [X] I Agree

**Comment by Akshayvs1** [comment]
Try getting a new api key and using that edit the config.js and upload metadata . Then create new contract

**Comment by StartUpDream** [comment]
This worked thank you
