### ISSUE TITLE
[Bug]: error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by gabyiscoding** [codeSTACKr/create-10k-nft-collection#143]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

I've seen several people here with same issue but don't believe there is a solution yet. 

it uploads json for some.. but majority it doesn't.

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Protect your information

- [X] I Agree

**Comment by gabyiscoding** [comment]
minor syntax error

**Comment by ADRIhein2** [comment]
hi, i have the same issue, did u find how to fix it ?
