### ISSUE TITLE
Undo - Fail Upload Images and Meta

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/create-10k-nft-collection#49]
Hello i uploaded 600 Images and 600 Metadata.
Then i realized that my NamePrefix for the NFT is wrong.

Now i want to clean the uploaded data and uploade the right images with right metadata for mint.

I dont minted the first 600 NFTs. 
When i now upload again 600 Images and metadata and then mint will there only be minted the secound 600 NFTs or all 1200 wich was uploaded before.

Is there a way to clean bevore i uploade and mint?

**Comment by codeSTACKr** [comment]
If you haven't minted them then there will only be 600 after you upload the corrected metadata. No need to upload the images again.
