### ISSUE TITLE
Polygon but still need Fee

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/create-10k-nft-collection#51]
Hey normaly when i add my NFTs over the Polygon chain and not over the ETH chain its Fee free and i dont need to pay to list a Price.
But when i use your minter and configurate polygon in the mint.js i stell need to pay fee when i try to sell my nfts with a price.

Is there a solution for this?

**Comment by codeSTACKr** [comment]
There are no fees to sell. There is only one fee from Opensea to verify your wallet. And that fee is very small, only cents.
