### ISSUE TITLE
Reveal Error

### ISSUE THREAD

**Issue by ChristianErdtmann** [codeSTACKr/create-10k-nft-collection#53]
PS C:\PROGRAMMING_Projects\NFTMinter1000Oversea\video-source-code-create-nft-collection> node utils/nftport/revealNFTs.js 
ERROR STATUS: 429
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 429
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying
ERROR STATUS: 429
Retrying

**Comment by codeSTACKr** [comment]
429 is a server error and will require you to retry until successful.
