### ISSUE TITLE
utils/nftport/uploadFiles.js: line 1: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by Zherebyatyev** [codeSTACKr/create-10k-nft-collection#57]
**SOLVED**

Getting syntax error while trying to run **uploadFiles.js**.

**error:**
utils/nftport/uploadFiles.js: line 1: syntax error near unexpected token (' 
utils/nftport/uploadFiles.js: line 1: `const FormData = require("form-data");'

**Comment by Zherebyatyev** [comment]
SOLVED

**Comment by codeSTACKr** [comment]
There seems to be an issue with your code. Be sure you have downloaded the latest version of this repository.
