### ISSUE TITLE
Error 422

### ISSUE THREAD

**Issue by srivera113** [codeSTACKr/create-10k-nft-collection#58]
I get the following error when running utils/nftport/uploadMetas.js

ERROR STATUS: 422
Retrying
CATCH ERROR: TypeError: Cannot read properties of undefined (reading 'response')
Retrying

I have been getting this error for over a week and I'm not sure how to fix it.

**Comment by nertsydude** [comment]
I'm getting a similar issue except with a status 403. Tried just using the original uploadMetas.js file as described in the video but it looks like without the timer functionality, the requests are too quick upload successfully. Hope we can get a response soon.

**Comment by codeSTACKr** [comment]
422 is a server error, you will need to retry. 403 is an authentication error. In that case, check your API key.

**Comment by jdlewis052** [comment]
I'm still getting the server error (422). Even with the timer set to 10000, I'm unable to upload the metadata to IPFS. I've retried with the original uploadMetas.js but with an error throughout saying "quota_limit" "Too many requests hit the API too quickly."
