### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by KaiWenF** [codeSTACKr/create-10k-nft-collection#59]
Have you run your code lately and it still works for you?  The code in the utils folder works with no problems at all but the code in the nftport folder is not working especially the uploadFiles.js file and it is VERY confusing as to how to resolve the problem.  Even doing the fix the you suggested is not resolving the problem.  I am a .net developer but my world is c# and vb.net.  Not so much with javascript and Node JS is super confusing with the consent updates.  I usually can figure coding problems out by reading the code and following the logic, but this is not a logic problem but rather some type of compatibility issue which makes it very confusing on how to fix the problem.  If I can't figure out the problem very easily and I am a developer I know it has to be madding to a none developer trying to resolve the problem.  Could you please review the newest version of your uploadFiles.js because the code in the video is vastly different than what you have in GIT?  I would love to use your solution but it is almost like working a full time job trying to resolve issues in the uploadFiles.js file.   I most likely will not be able to use the files in the nftport folder which is a shame, and will have to fine another solution to upload my NFT files.  Sorry for the long message but I really love the solution and appreciate the effort you put into it.   Regards

**Comment by codeSTACKr** [comment]
You will find the solution to this issue here: https://github.com/codeSTACKr/create-10k-nft-collection#es-module-error-err_require_esm
