### ISSUE TITLE
[Bug]: Uploading metas returns TypeError: Cannot read properties of undefined (reading 'edition')

### ISSUE THREAD

**Issue by DasKeg** [codeSTACKr/create-10k-nft-collection#67]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

const uploadedMeta = `${basePath}/build/ipfsMetas/${metaData.custom_fields.edition}.json`;
                                                                                 ^
TypeError: Cannot read properties of undefined (reading 'edition')

At the top of the script it makes the directory ipfsMetas, but its an empty directory, theres no files in it. My assumption is there is know way for the program to know where to look for the custom_fields.edition. is it defined somewhere?

relevent code 

if (!fs.existsSync(path.join(`${basePath}/build`, "/ipfsMetas"))) {
  fs.mkdirSync(path.join(`${basePath}/build`, "ipfsMetas"));
}

async function main() {
  const files = fs.readdirSync(readDir);
  files.sort(function(a, b){
    return a.split(".")[0] - b.split(".")[0];
  });
  for (const file of files) {
    if (file !== "_metadata.json" && file !== "_ipfsMetas.json") {
      let jsonFile = fs.readFileSync(`${readDir}/${file}`);
      let metaData = JSON.parse(jsonFile);
      const uploadedMeta = `${basePath}/build/ipfsMetas/${metaData.custom_fields.edition}.json`;

### What have you tried?

I looked through the program where the location would have been defined.  I searched the forums and google to see if anyone else had the same issue. 

### Relevant log output

```shell
const uploadedMeta = `${basePath}/build/ipfsMetas/${metaData.custom_fields.edition}.json`;
                                                                                 ^


TypeError: Cannot read properties of undefined (reading 'edition')
```

### Protect your information

- [X] I Agree

**Comment by DasKeg** [comment]
Found issue in thread..

**Comment by Mistermatthews** [comment]
@DasKeg what was the fix?
