### ISSUE TITLE
[Bug]: No image preview even after refreshing metadata

### ISSUE THREAD

**Issue by tenumars** [codeSTACKr/create-10k-nft-collection#68]
### Version

- [x] Yes

### General Question

- [X] No

### What happened?

No image preview on opensea, even after refreshing metadata and waiting for a few hours. Nothing is showing up.
![image](https://user-images.githubusercontent.com/98669318/151678713-48ea4ecf-7cba-438f-8776-26c415e9b873.png)

### What have you tried?

Refreshing metadata, then waiting
waiting 12+hrs

### Protect your information

- [X] I Agree

**Comment by thepeanutgalleryandco** [comment]
@tenumars your images will never load as the metadata of your NFTs is not correct.

https://testnets-api.opensea.io/asset/0x881f8d2b14187bbee7b9c3c129d83a97c81ad66a/4/validate - This URL shows you to the endpoint of the metadata for your NFT.

https://opensea.mypinata.cloud/ipfs/bafkreibr33gxwk4k4xyiaefjvcwtwadpmncjn5fftg62tx5ef4g3wksm5u - This is the metadata URL and it shows that the image field points to https://api.nftport.xyz/v0/files/4.png which does not exist, so no image can be shown for your NFTs.

Somewhere you did something incorrectly and your actual NFT image URLs on IPFS is not in your metadata that you linked to the token / NFT.

**Comment by tenumars** [comment]
So what would I do to fix it? I followed the video exactly.

**Comment by thepeanutgalleryandco** [comment]
@tenumars you need to check as to why your metadata json files that got uploaded contains "https://api.nftport.xyz/v0/files/4.png" as the URL instead of your IPFS URLs. This is where your error lies.

**Comment by tenumars** [comment]
So how would I fix it? Do I need to change in the uploadFiles.js line 56?
`      let url = "https://api.nftport.xyz/v0/files/";`

**Comment by tenumars** [comment]
Nvm, figured it out, had an extra slash that should not have been there.

**Comment by tenumars** [comment]
nope, still didn't work. I am out of 'mints" on rinkeby, so am having to use the polygon contract. I upload them to IPFS, then the metadata, then mint, but it still does not have the image and I see in the metadata that the url is incorrect still. How would I fix that?

**Comment by tenumars** [comment]
Upload images should do it, at least it did for me. It updates the metadata with the address

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
