### ISSUE TITLE
NOK: Minting limit exceed on polygon Retrying

### ISSUE THREAD

**Issue by cagri27** [codeSTACKr/create-10k-nft-collection#69]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

I did everyting right but when i go to terminal and run: node utils/nftport/mint.js
at first it is going well and minting NFTs. but after minting 140 NFTs it says; NOK: Minting limit exceed on polygon Retrying

How can i solve this issue?

### What have you tried?

Google it.

### Protect your information

- [X] I Agree

**Comment by tenumars** [comment]
I have the same error, after 126 successful.

**Comment by tenumars** [comment]
Did you find a  fix? Still trying to get mine to work on the testnet, hopefully fixed an error

**Comment by cagri27** [comment]
No i did not find solutioun yet.

**Comment by thepeanutgalleryandco** [comment]
Go to https://docs.nftport.xyz/docs/nftport/b3A6MzQ2MDk3ODI-user-settings and see how many mints you received for free. It could be 10000, 1000, 500 or 100. Then, if you have no mints left and want to mint more, then sign up to the Growth plan on Nftport which costs $99 for 500 mints and then about $63 for the 500 there after.

**Comment by cagri27** [comment]
https://www.youtube.com/watch?v=AaCgydeMu64&list=WL&index=2&t=2987s but in this video, it says all the prosess are totaly free.

**Comment by volkovecom** [comment]
Dear,

Error: Too many requests pending: https://nftport.notion.site/Error-Too-many-requests-pending-5898cdfa688a40e9964c8a9f6fecfa3f

https://nftport.statuspage.io/

**Comment by codeSTACKr** [comment]
you have reached the limit of your current NFTPort plan. This is not an issue with the code base.

**Comment by harmen07** [comment]
mint limit was not addressed in the tutorials. do we have to restart the entire process after getting a subscription, or we can just start back from where we left off ?
