### ISSUE TITLE
[Bug]: Generate

### ISSUE THREAD

**Issue by AirmanMelvin** [codeSTACKr/create-10k-nft-collection#70]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened!
Missing script: "generate"

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
(c) Microsoft Corporation. All rights reserved.

C:\Users\Melvin\Documents\create-10k-nft-collection-1.1.0>npm run generate
npm ERR! Missing script: "generate"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Melvin\AppData\Local\npm-cache\_logs\2022-01-30T15_15_38_861Z-debug.log
```

### Protect your information

- [X] I Agree

**Comment by thepeanutgalleryandco** [comment]
Type in "npm run"  as per the suggestion and see what commands are available. Sometimes, you might need to go one directory deeper to get to the folder with the actual code. Did you run the npm install commands as well?

**Comment by AirmanMelvin** [comment]
Hi,
I re-installed VS code.
Solved the problem. Thanks for your help.
