### ISSUE TITLE
[Bug]: ERR_INVALID_ARG_TYPE received undefined

### ISSUE THREAD

**Issue by tenumars** [codeSTACKr/create-10k-nft-collection#72]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

While I am trying to upload the files, I get an error of 

`error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined`

while uploading. I have made sure there are no hyphens in the file names, and all the folders are spelled the exact same way that they are in the config.js 
I have created 5 (to test) and only 2 will upload at once. It is seemingly random which 2 it does 'choose' and upload, but I have no way of knowing. This is the full error message(s)
```
node utils/nftport/uploadFiles.js
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1.png uploaded & 1.json updated!
2.png uploaded & 2.json updated!
```

Checked to make sure there are no inconcesiencies

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Relevant log output

```shell
node utils/nftport/uploadFiles.js
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
error:TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
1.png uploaded & 1.json updated!
2.png uploaded & 2.json updated!
```

### Protect your information

- [X] I Agree

**Comment by Mugzy1** [comment]
Hi, i saw that you closed the issue so have you found the solution? If yes can you share it with us? because im having exactly the same issue please.

**Comment by tenumars** [comment]
Yes, I did. What I ended up doing was just deleting the entire folder (except for the layers) and redownloading the latest version and used that. That seemed to work, all you need though is the npm install, no other packages. That has worked since for me
