### ISSUE TITLE
All images are low quality. Ugly! Can't even tell what they are.

### ISSUE THREAD

**Issue by Glitchbes** [codeSTACKr/create-10k-nft-collection#73]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

When I run "Generate"  all my images come back with low gamma, they look awful, like something from a 1930s computer, can't even tell what they are. The graphics look like black and white shedded newspaper.

### What have you tried?

I went to YouTube and Google but no help.

### Protect your information

- [X] I Agree

**Comment by thepeanutgalleryandco** [comment]
@Glitchbes did you make all of your layer items on the same Canvas size?

**Comment by Glitchbes** [comment]
Both the background and layers are all the same zize, height and width, exported as png at 32 bit, platform used is Gimp.

**Comment by Glitchbes** [comment]
![image](https://user-images.githubusercontent.com/98601257/152084125-293115e9-f9f0-4202-9b4a-64a167a0edf0.png)

**Comment by codeSTACKr** [comment]
What is the size of your layers and the size of your `format` width and height in the `config.js` file?
If these are different then the image will be distorted.

**Comment by Cadevens1** [comment]
Hi there! Having the same issue. All exported in high quality png but when images generate they are low quality. Sizing of layers are all the same and I have even adjusted the width/ height of format to see if it helps. Size H: 608 W:740.  What else should I be looking at to get a clear image output? Thanks so much for your help

**Comment by Glitchbes** [comment]
I ended up importing all mine that I made in Gimp into Figma, then exporting them out of Figma into a new layers folder.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Cadevens1** [comment]
Interesting— I initially created mine in Figma and exported them straight from platform. Did the Figma and new layer folder solve your issue? Mine still are really low quality and pixelated.

**Comment by Glitchbes** [comment]
I had to add a frame into each section of my layers, it's complicated to explain in "typing".

I played with it for several hours before getting it all correct. Wasn't as easy as it should have been. But yes all my images are now correct, when ran through generator.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Cadevens1** [comment]
> 

Got it— I have frames exactly the same for each layer. But I noticed after adjusting a few times that my height and width, don’t seem to change output when i adjust them within code. This could be causing the distortion , but am unsure how to fix. Any suggestions?

**Comment by Glitchbes** [comment]
I just selected all images, frame included (ctrl+a), that were within frame. Then put h/w in, it lined them all up in one go.

Powered by Cricket Wireless
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
